### ISSUE TITLE
Comentarios Project Feedback

### ISSUE THREAD

**Issue by ChristianRL23** [gabyrramos/DEV013-dataverse#22]
### Objetivos de aprendizaje pendientes
- Diferenciar entre expresiones (expressions) y sentencias (statements)
- Git: Integración de cambios entre ramas (branch, checkout, fetch, merge, reset, rebase, tag)
- Few shot prompting

Además recomiendo reforzar el OA de test.

### Sugerencias para próximo proyecto
- Hacer Pull Requests. Es decir, que tu compañera haga fork del proyecto
- Esforzarse por mantener el código en inglés (si es posible)
- Tener mucho ojo en el README para saber cuales son los requisitos para solicitar PF
- En viernes flex o en otro momento adecuado terminar tests de OA's y e2e pendientes
- Darle títulos más descriptivos a los commits

### Comentario
Muchas felicidades Gabi por haber terminado tu proyecto, fue muy bueno y la explicación también. Valió la pena quedarse un par de días para reforzar tests, serán muy útiles para el siguiente proyecto.
Te recomiendo tener mucho ojo al readme para saber cuales son los requisitos para solicitar PF y que en algún momentos del viernes flex puedas terminar los tests de OA's y e2e que quedaron pendientes.
Sigue investigando recursos y profundizando en los OA's tal como lo has hecho hasta ahora.

**Comment by gabyrramos** [comment]
Muchas Gracias Chris, me olvide de cerrar este issue pero muchas gracias por estos consejos, me he dedicado a estudiar y mejorar estas observaciones.
